# Generated by Django 5.2.12 on 2026-03-29 20:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stokvel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contribution_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payout_day', models.IntegerField(help_text='Day of month payouts happen')),
                ('created_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='contribution',
            name='status',
            field=models.CharField(choices=[('paid', 'Paid'), ('missed', 'Missed'), ('late', 'Late')], default='paid', max_length=10),
        ),
        migrations.AddField(
            model_name='member',
            name='stokvel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contributions.stokvel'),
        ),
    ]
