# Generated by Django 5.2.12 on 2026-03-29 20:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0002_stokvel_contribution_status_member_stokvel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('skipped', 'Skipped')], default='pending', max_length=10)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contributions.member')),
                ('stokvel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contributions.stokvel')),
            ],
        ),
    ]
